(()=>{
 const c=document.querySelector('#content'),r=document.querySelector('#route-name');
 const state={price:null,city:null,channels:[],marketingBudget:50000,launchMonth:null};
 const listeners=new Set();
 const euro=v=>v===null?'Not selected':new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v);
 window.LumenStrategy={getState:()=>({...state}),subscribe:fn=>(listeners.add(fn),()=>listeners.delete(fn))};
 const update=patch=>{Object.assign(state,patch);listeners.forEach(fn=>fn({...state}))};
 const render=data=>{const review=[['Price',euro(state.price)],['City / region',state.city||'Not selected'],['Channel mix',state.channels.length?state.channels.join(', '):'Default evidence-based mix'],['Marketing budget',euro(state.marketingBudget)],['Launch month',state.launchMonth||'Not selected']];
 c.innerHTML=UI.pageHeader({eyebrow:'Plan / strategy builder',title:'Strategy Builder',description:'Set the five inputs that directly support the Germany launch decision.'})+UI.section({title:'Launch decision inputs',description:'Price, city, channels, budget, and timing are the core choices required by the case brief.',body:UI.filterControls({body:UI.select({id:'strategy-price',label:'Candidate price',value:String(state.price||''),options:[{label:'Not selected',value:''},...data.prices.map(v=>({label:'€'+v.toFixed(2),value:String(v)}))]})+UI.select({id:'strategy-city',label:'City / region',value:state.city||'',options:[{label:'Not selected',value:''},...data.cities.map(v=>({label:v,value:v}))]})+UI.multiSelect({id:'strategy-channels',label:'Channel mix (optional)',options:data.channels.map(v=>({label:v,value:v}))})+UI.slider({id:'strategy-budget',label:'Marketing budget scenario',min:0,max:200000,step:1000,value:state.marketingBudget,suffix:' EUR'})+UI.select({id:'strategy-month',label:'Launch month',value:state.launchMonth||'',options:[{label:'Not selected',value:''},...data.months.map(v=>({label:v,value:v}))]})})})+UI.twoColumn({primary:UI.section({title:'Strategy review',description:'These inputs are passed to the Decision Engine when you open Decide → Recommendation.',body:UI.dataTable({headers:['Field','Selected value'],rows:review})}),secondary:UI.section({title:'Integration status',description:'Inputs are live, not placeholders.',body:UI.businessImplication({body:'Change any field, then open Decision Engine. The recommendation, economics, score, risks, and trade-off will be recalculated from these core inputs.'})+UI.state({type:'mock',message:'Empty or partial inputs use documented defaults.'})})});
 UI.activate(c); const q=id=>c.querySelector(id); q('#strategy-price').addEventListener('change',e=>{update({price:e.target.value?Number(e.target.value):null});render(data)});q('#strategy-city').addEventListener('change',e=>{update({city:e.target.value||null});render(data)});q('#strategy-month').addEventListener('change',e=>{update({launchMonth:e.target.value||null});render(data)});q('#strategy-budget').addEventListener('input',e=>{update({marketingBudget:Number(e.target.value)||0});render(data)});q('#strategy-channels').addEventListener('change',e=>{update({channels:[...e.target.selectedOptions].map(o=>o.value)});render(data)});
 };
 const load=async()=>{if(location.hash.slice(1)!=='/plan/strategy')return;r.textContent='Strategy Builder';c.innerHTML=UI.state({type:'loading'});try{const [p,ci,ch,t]=await Promise.all([DiscoverData.pricingLab(),DiscoverData.cityPrioritizer(),DiscoverData.channelOptimizer(),DiscoverData.timingEngine()]);render({prices:p.options.map(x=>x.price),cities:ci.cities.map(x=>x.name),channels:ch.rows.map(x=>x.name),months:t.months.map(x=>new Date(2026,x.month-1,1).toLocaleString('en',{month:'long'}))})}catch(e){c.innerHTML=UI.state({type:'error',message:'Strategy input data is unavailable.'})}};addEventListener('hashchange',load);load();
})();
