(()=>{
 const c=document.querySelector('#content'),r=document.querySelector('#route-name');
 const state={price:null,city:null,channels:[],marketingBudget:50000,launchMonth:null,targetSegment:null,objective:null};
 const listeners=new Set();
 const euro=v=>v===null?'Not selected':new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v);
 window.LumenStrategy={getState:()=>({...state}),subscribe:fn=>(listeners.add(fn),()=>listeners.delete(fn))};
 const update=patch=>{Object.assign(state,patch);listeners.forEach(fn=>fn({...state}))};
 const render=data=>{const review=[['Price',euro(state.price)],['City / region',state.city||'Not selected'],['Channel mix',state.channels.length?state.channels.join(', '):'Default evidence-based mix'],['Marketing budget',euro(state.marketingBudget)],['Launch month',state.launchMonth||'Not selected'],['Target segment',state.targetSegment||'Not selected'],['Strategic objective',state.objective||'Not selected']];
 c.innerHTML=UI.pageHeader({eyebrow:'Plan / strategy builder',title:'Strategy Builder',description:'Set inputs and see them flow into the Decision Engine recommendation.'})+UI.section({title:'1. Commercial choices',body:UI.filterControls({body:UI.select({id:'strategy-price',label:'Candidate price',value:String(state.price||''),options:[{label:'Not selected',value:''},...data.prices.map(v=>({label:'€'+v.toFixed(2),value:String(v)}))]})+UI.select({id:'strategy-city',label:'City / region',value:state.city||'',options:[{label:'Not selected',value:''},...data.cities.map(v=>({label:v,value:v}))]})+UI.multiSelect({id:'strategy-channels',label:'Channel mix (optional)',options:data.channels.map(v=>({label:v,value:v}))})})})+UI.section({title:'2. Launch choices',body:UI.filterControls({body:UI.slider({id:'strategy-budget',label:'Marketing budget scenario',min:0,max:200000,step:1000,value:state.marketingBudget,suffix:' EUR'})+UI.select({id:'strategy-month',label:'Launch month',value:state.launchMonth||'',options:[{label:'Not selected',value:''},...data.months.map(v=>({label:v,value:v}))]})+UI.select({id:'strategy-segment',label:'Target segment',value:state.targetSegment||'',options:[{label:'Not selected',value:''},...data.segments.map(v=>({label:v,value:v}))]})+UI.select({id:'strategy-objective',label:'Strategic objective',value:state.objective||'',options:[{label:'Not selected',value:''},{label:'Build awareness',value:'Build awareness'},{label:'Validate demand',value:'Validate demand'},{label:'Drive contribution',value:'Drive contribution'}]})})})+UI.twoColumn({primary:UI.section({title:'Strategy review',description:'These inputs are passed to the Decision Engine when you open Decide → Recommendation.',body:UI.dataTable({headers:['Field','Selected value'],rows:review})}),secondary:UI.section({title:'Integration status',description:'Inputs are live, not placeholders.',body:UI.businessImplication({body:'Change any field, then open Decision Engine. The recommendation, economics, score, risks, and trade-off will be recalculated from the selected inputs.'})+UI.state({type:'mock',message:'Empty, partial, or unusual inputs use documented defaults and remain safe to evaluate.'})})});
 UI.activate(c); const q=id=>c.querySelector(id); q('#strategy-price').addEventListener('change',e=>{update({price:e.target.value?Number(e.target.value):null});render(data)});q('#strategy-city').addEventListener('change',e=>{update({city:e.target.value||null});render(data)});q('#strategy-month').addEventListener('change',e=>{update({launchMonth:e.target.value||null});render(data)});q('#strategy-segment').addEventListener('change',e=>{update({targetSegment:e.target.value||null});render(data)});q('#strategy-objective').addEventListener('change',e=>{update({objective:e.target.value||null});render(data)});q('#strategy-budget').addEventListener('input',e=>{update({marketingBudget:Number(e.target.value)||0});render(data)});q('#strategy-channels').addEventListener('change',e=>{update({channels:[...e.target.selectedOptions].map(o=>o.value)});render(data)});
 };
 const load=async()=>{if(location.hash.slice(1)!=='/plan/strategy')return;r.textContent='Strategy Builder';c.innerHTML=UI.state({type:'loading'});try{const [p,ci,ch,cu,t]=await Promise.all([DiscoverData.pricingLab(),DiscoverData.cityPrioritizer(),DiscoverData.channelOptimizer(),DiscoverData.customerSummary(),DiscoverData.timingEngine()]);render({prices:p.options.map(x=>x.price),cities:ci.cities.map(x=>x.name),channels:ch.rows.map(x=>x.name),segments:cu.segments.map(x=>x.name),months:t.months.map(x=>new Date(2026,x.month-1,1).toLocaleString('en',{month:'long'}))})}catch(e){c.innerHTML=UI.state({type:'error',message:'Strategy input data is unavailable.'})}};addEventListener('hashchange',load);load();
})();
